#!/bin/bash

# 分卷打包
# tar cvzf - ./ |split -d -b 30m - linux_mcu_build_env-image.bin.zip

# 解包
cat linux_mcu_build_env-image.bin.zip* >image.bin.zip.tar.gz
tar xzvf image.bin.zip.tar.gz
unzip linux_mcu_build_env-image.bin.zip

# docker载入
docker load < linux_mcu_build_env-image.bin

# 查看
docker images

rm -rf image.bin.zip.tar.gz linux_mcu_build_env-image.bin linux_mcu_build_env-image.bin.zip








